apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: microservice-a
  namespace: apps
spec:
  replicas: 3
  selector:
    matchLabels:
      app: microservice-a
  template:
    metadata:
      labels:
        app: microservice-a
        version: v2
    spec:
      containers:
      - name: microservice-a
        image: marcelocollyer/microservice-a:v0.0.10
        ports:
        - containerPort: 3000
  strategy:
    canary:
      steps:
      - setWeight: 30
      - pause: {}
      - setWeight: 60
      - pause: {}
      - setWeight: 100
      - pause: {}   
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: microservice-b
  namespace: apps
spec:
  replicas: 3
  selector:
    matchLabels:
      app: microservice-b
  template:
    metadata:
      labels:
        app: microservice-b
        version: v2
    spec:
      containers:
      - name: microservice-b
        image: marcelocollyer/microservice-b:v0.0.10
        ports:
        - containerPort: 8080  
  strategy:
    canary:
      steps:
      - setWeight: 30
      - pause: {}
      - setWeight: 60
      - pause: {}
      - setWeight: 100
      - pause: {}   
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: microservice-c
  namespace: apps
spec:
  replicas: 3
  selector:
    matchLabels:
      app: microservice-c
  template:
    metadata:
      labels:
        app: microservice-c
        version: v2
    spec:
      containers:
      - name: microservice-c
        image: marcelocollyer/microservice-c:v0.0.10
        ports:
        - containerPort: 8000
  strategy:
    canary:
      steps:
      - setWeight: 30
      - pause: {}
      - setWeight: 60
      - pause: {}
      - setWeight: 100
      - pause: {}   
---
apiVersion: v1
kind: Service
metadata:
  name: microservice-a
  namespace: apps
spec:
  selector:
    app: microservice-a
  ports:
  - port: 8080
    targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: microservice-b
  namespace: apps
spec:
  selector:
    app: microservice-b
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: microservice-c
  namespace: apps
spec:
  selector:
    app: microservice-c
  ports:
  - port: 8000
    targetPort: 8000