apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: microservice-a
  namespace: apps
spec:
  replicas: 3
  selector:
    matchLabels:
      app: microservice-a
  template:
    metadata:
      labels:
        app: microservice-a
        version: v1
    spec:
      containers:
      - name: microservice-a
        image: marcelocollyer/microservice-a:v1
        ports:
        - containerPort: 3000
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {duration: 60s}
      - setWeight: 40
      - pause: {duration: 60s}
      - setWeight: 60
      - pause: {duration: 60s}
      - setWeight: 80
      - pause: {duration: 60s}
      - setWeight: 100
      canaryService: microservice-a-canary
      stableService: microservice-a-stable
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: microservice-b
  namespace: apps
spec:
  replicas: 3
  selector:
    matchLabels:
      app: microservice-b
  template:
    metadata:
      labels:
        app: microservice-b
        version: v1
    spec:
      containers:
      - name: microservice-b
        image: marcelocollyer/microservice-b:v1
        ports:
        - containerPort: 8080
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {duration: 60s}
      - setWeight: 40
      - pause: {duration: 60s}
      - setWeight: 60
      - pause: {duration: 60s}
      - setWeight: 80
      - pause: {duration: 60s}
      - setWeight: 100
      canaryService: microservice-b-canary
      stableService: microservice-b-stable     
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: microservice-c
  namespace: apps
spec:
  replicas: 3
  selector:
    matchLabels:
      app: microservice-c
  template:
    metadata:
      labels:
        app: microservice-c
        version: v1
    spec:
      containers:
      - name: microservice-c
        image: marcelocollyer/microservice-c:v1
        ports:
        - containerPort: 8000
  strategy:
    canary: 
      steps:
      - setWeight: 20
      - pause: {duration: 60s}
      - setWeight: 40
      - pause: {duration: 60s}
      - setWeight: 60
      - pause: {duration: 60s}
      - setWeight: 80
      - pause: {duration: 60s}
      - setWeight: 100
      canaryService: microservice-c-canary
      stableService: microservice-c-stable